<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>sod_basic_mod</AssemblyName>
    <Product>SOD Basic Mod</Product>
    <Version>1.0.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>sod_basic_mod</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="UnityEngine.Modules" Version="6000.0.58" IncludeAssets="compile" />
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Mirror">
      <HintPath>lib/Mirror.dll</HintPath>
    </Reference>
    <Reference Include="HarmonyLib">
      <HintPath>lib/0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Dew.Contents">
      <HintPath>lib/Dew.Content.dll</HintPath>
    </Reference>
    <Reference Include="Dew.External">
      <HintPath>lib/Dew.External.dll</HintPath>
    </Reference>
    <Reference Include="Dew.Core">
      <HintPath>lib/Dew.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
